name: build-test-deploy
on: workflow_dispatch

jobs:

  build:
    runs-on: ubuntu-latest
    steps: 
      - name: Building an app
        run: 
          echo "Building JAVA app"

  test:
    runs-on: ubuntu-latest
    needs: build
    steps: 
      - name: Testing an app 
        run: 
          echo "tesing an JAVA app"

  deploy: 
    runs-on: ubuntu-latest
    needs: test
    steps: 
      - name: Deploying an app
        run: 
          echo "Deploying JAVA app"               